### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by nickbetteridge** [dannywillems/ocaml-js-stdlib#2]
Could you possibly include a simple example?

**Comment by dannywillems** [comment]
@nickbetteridge What kind of examples are you interested in?

**Comment by nickbetteridge** [comment]
Hi Danny - thanks for getting back. Just been through the example of `https://github.com/LexiFi/gen_js_api/blob/master/examples/misc/test_jquery.ml` and have got the hang of it. I need to embed some jquery components and found that gen_js_api was a good way to go - but it's now dawning on me the amount of work required to write an interface file - especially when the components are large. Wish there was a parser/generator available!
