### ISSUE TITLE
$(this)

### ISSUE THREAD

**Issue by nickbetteridge** [dannywillems/ocaml-js-stdlib#3]
Hi
I'm beginning to use ocaml-js-stdlib (great lib!) - but can't work out how to derive 'this' with selector - any ideas?
Cheers
Nick

**Comment by nickbetteridge** [comment]
Ah - perhaps it's built-in - Js_jquery.selector this

**Comment by dannywillems** [comment]
@nickbetteridge `Js_jquery.selector "div"` it's equivalent to `$("div")`.

To be honest, I never used `jquery` module and it's me who wrote this: I always use `js_dom`. I'm sure there are lots of missing thing. Don't hesitate to contribute.

**Comment by nickbetteridge** [comment]
Great, thanks! So far I haven't needed to add anything! Seems pretty complete.
